swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: localhost:8888
basePath: /api
schemes:
  - http
securityDefinitions:
  #  BasicAuth:
  #    type: basic
  ApiKeyAuth:
    type: apiKey
    in: header
    name: X-API-Key
#  OAuth2:
#    type: oauth2
#    flow: accessCode
#    authorizationUrl: https://example.com/oauth/authorize
#    tokenUrl: https://example.com/oauth/token
#    scopes:
#      read: Grants read access
#      write: Grants write access
#      admin: Grants read and write access to administrative information


paths:
  /authentication:
    post:
      tags:
        - Login
      summary: Return token
      parameters:
        - in: body
          name: user
          schema:
            properties:
              user_name:
                type: string
              password:
                type: string
            required:
              - user_name
              - password
      responses:
        200:
          description: OK

  /users:
    description: aaaa
    post:
      tags:
        - User
      summary: Creates a new user.
      parameters:
        - in: body
          name: user
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: OK
    get:
      tags:
        - User
      summary: Returns a user by ID.
      parameters:
        - in: path
          name: userId
          required: true
          type: integer
          minimum: 1
          description: Parameter description in Markdown.
      responses:
        200:
          description: OK
definitions:
  User:
    properties:
      id:
        type: integer
      name:
        type: string
    # Both properties are required
    required:
      - id
      - name